Id b 14
Ionefor/PawShelter pull request #25
Opened 2024-11-08 18:51 UTC by Ionefor

2024-11-09 07:38 UTC, KirillSachkov commented on backend/src/PawShelter.API/Controllers/Volunteer/Requests/GetFilteredPetsWithPaginationRequest.cs
> +    FilteringParamsDto? FilteringParamsDto,
не нужно в названиях свойств прибавлять в конце dto, у тебя само свойство dto и оно находится в request, и так понятно что это dto будет

2024-11-09 09:13 UTC, Ionefor commented
Сортировка и фильтрация в хэндлере нормально выглядит? Мне не особо нравится так, как можно улучшить?

2024-11-09 10:17 UTC, KirillSachkov commented
> Сортировка и фильтрация в хэндлере нормально выглядит? Мне не особо нравится так, как можно улучшить?

выглядит нормально, часто так и приходится делать. но можно использовать builder pattern, это когда ты у query например вызываешь метод на методом по цепочке допустим так, попробуй реализовать. Здесь используется паттерн Builder

![изображение](https://github.com/user-attachments/assets/760e6539-dcfd-4b40-ab7b-00fdf7d1f86d)

2024-11-10 14:50 UTC, Ionefor commented
Долго думал как это лучше сделать, решил попробовать так, первый раз воспользовался рефлексией. Не совсем разобрался как она работает и пока не понимаю нормально ли ее использовать в таких местах или нет. Жду комментарий про все это)

2024-11-11 08:15 UTC, KirillSachkov requested changes

2024-11-11 08:15 UTC, KirillSachkov commented on backend/src/PawShelter.Application/Extensions/QueriesExtensions.cs
> +    public static IQueryable<TSource> ApplyFilter<TSource>(
Никогда не используй рефлексию в таких задачах, рефлексия довольно медленная, использует много ресурсов, она неявная, нечитаемая.

Я наверное привёл неудачный пример названия методов. Попробуй сделать явный builder, не просто ApplyFilter, а например что-то такое. Если не получится, то ничего страшного, думаю, что позже посвятим этому занятие

![изображение](https://github.com/user-attachments/assets/30dc4fbc-569d-4c17-893d-a95eacd287c4)

2024-11-11 08:16 UTC, KirillSachkov commented on backend/src/PawShelter.Application/Extensions/QueriesExtensions.cs
> +    public static IQueryable<TSource> ApplyFilter<TSource>(
Если не выйдет, то лучше явно вызывать методы фильтрации, чем использовать рефлексию

2024-11-11 11:00 UTC, merged