add volunteer feature creation
Ionefor/PawShelter pull request #8
Opened 2024-10-07 14:13 UTC by Ionefor

2024-10-07 14:26 UTC, Ionefor commented
В классе CreateVolunteerHandler у меня вопрос в комментах.

2024-10-08 05:21 UTC, YaraOduvanchik requested changes

2024-10-08 05:21 UTC, YaraOduvanchik commented on backend/src/PawShelter.API/Controllers/VolunteerController.cs
> +            var result = await handler.Handle(request, cancellationToken);
Прочитай задание, там написано, что должна создаваться CreateVolunteerCommand, комманда, которая используется в сервисе в слое Application

2024-10-08 05:21 UTC, YaraOduvanchik commented on backend/src/PawShelter.Application/Volunteers/CreateVolunteer/CreateVolunteerHandler.cs
> +               Нужно ли проверять в списках что все хорошо? И если нужно, то делать так?
Пока что нужно проверять, в дальнейшем мы уберём проверки

2024-10-08 05:21 UTC, YaraOduvanchik commented on backend/src/PawShelter.Application/Volunteers/CreateVolunteer/CreateVolunteerRequest.cs
> +    List<RequisiteDto>? requisites, List<SocialNetworkDto>? socialNetworks);
Вместо List тут лучше использовать IEnumerable

2024-10-08 06:29 UTC, YaraOduvanchik commented on backend/src/PawShelter.Application/Volunteers/CreateVolunteer/CreateVolunteerCommand.cs
> +        string description, string email, string phoneNumber, int experience,
Лучше сделать переносы, чтобы каждое поле было на новой строке, так более читабельнее будет

2024-10-08 06:29 UTC, YaraOduvanchik commented on backend/src/PawShelter.Application/Volunteers/CreateVolunteer/CreateVolunteerRequest.cs
> +        IEnumerable<RequisiteDto>? requisites, IEnumerable<SocialNetworkDto>? socialNetworks)
Лучше сделать переносы, чтобы каждое поле было на новой строке, так более читабельнее будет

2024-10-08 08:29 UTC, merged