Validation command
Ionefor/PawShelter pull request #9
Opened 2024-10-09 14:26 UTC by Ionefor

Пока что не совсем понял как нормально доделать валидацию с ошибками, думаю дальше разберусь, для возвращения списка ошибок посмотрел немного занятие 13, вроде получилось, но какая то проблема с ошибками, в контроллере написал об этом. И в целом не совсем ясно с Envelope, он находится в слое c API, а валидация в Application

2024-10-09 15:05 UTC, YaraOduvanchik requested changes

2024-10-09 15:05 UTC, YaraOduvanchik commented on backend/src/PawShelter.Application/Volunteers/CreateVolunteer/CreateVolunteerCommandValidator.cs
> +            MustBeValueObject(l => Name.Create(l.lastName));
Мы неможем делать так.

Ты должен написать: MustBeValueObject(f => FullName.Create(f.firstName, f.middleName, f.lastName)).

Или то что я написал ниже, я точно не знаю как у тебя ValueObject создаётся этот

2024-10-09 15:05 UTC, YaraOduvanchik commented on backend/src/PawShelter.Application/Volunteers/CreateVolunteer/CreateVolunteerCommandValidator.cs
> +            MustBeValueObject(r => Name.Create(r.name)).
Нужно написать просто MustBeValueObject(r => Requisite.Create(Name.Create(r.name), Description.Create(r.description));

2024-10-09 15:07 UTC, YaraOduvanchik commented
> Пока что не совсем понял как нормально доделать валидацию с ошибками, думаю дальше разберусь, для возвращения списка ошибок посмотрел немного занятие 13, вроде получилось, но какая то проблема с ошибками, в контроллере написал об этом. И в целом не совсем ясно с Envelope, он находится в слое c API, а валидация в Application

Я написал в VolunteerController что нужно попробовать сделать, если не получится, напиши в технические вопросы в тг

2024-10-09 15:08 UTC, YaraOduvanchik commented on backend/src/PawShelter.API/Controllers/VolunteerController.cs
> +            //??
Обратись в технические вопросы если не получится

2024-10-09 19:36 UTC, Ionefor commented
Разобрался с ответом когда все хорошо, когда должен был быть код 400, вместо него приходил 500, это происходило когда валидировался VO состоящий из других VO, решил сделать VO состоящие из простых типов и все стало работать, так нормально? Если оставлять как было, то там почему то приходит ErrorType = null, не смог найти почему так происходит, скорее всего из за повторного вызова метода Create "MustBeValueObject(r => Requisite.Create(Name.Create(r.name), Description.Create(r.description)) ".

2024-10-10 07:26 UTC, YaraOduvanchik approved these changes

2024-10-10 07:30 UTC, YaraOduvanchik commented
> Разобрался с ответом когда все хорошо. Когда должен был быть код 400, вместо него приходил 500, это происходило когда валидировался VO состоящий из других VO, решил сделать VO состоящие из простых типов и все стало работать, так нормально? Если оставлять как было, то там почему то приходит ErrorType = null, не смог найти почему так происходит, скорее всего из за повторного вызова метода Create "MustBeValueObject(r => Requisite.Create(Name.Create(r.name), Description.Create(r.description)) ".

ErrorType был null, так как ты присваивал ему null в классе ResponseExtensions, в методе ToResponse(this UnitResult<Error> result), вот тут:
var envelope = Envelope.Error(
                [new(result.Error.Code, result.Error.Message, null)]);
                
Сейчас всё нормально так как ты делаешь просто error.ToErrorList(), и там не передаётся null

2024-10-10 08:47 UTC, merged